/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio
 */
public class Matrices extends javax.swing.JFrame {

    /**
     * Creates new form Matrices
     */
    public Matrices() {
        super("Operaciones con matrices");
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        a00 = new javax.swing.JTextField();
        a01 = new javax.swing.JTextField();
        a10 = new javax.swing.JTextField();
        a11 = new javax.swing.JTextField();
        a12 = new javax.swing.JTextField();
        a02 = new javax.swing.JTextField();
        a20 = new javax.swing.JTextField();
        a21 = new javax.swing.JTextField();
        a22 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        b00 = new javax.swing.JTextField();
        b01 = new javax.swing.JTextField();
        b02 = new javax.swing.JTextField();
        b12 = new javax.swing.JTextField();
        b22 = new javax.swing.JTextField();
        b11 = new javax.swing.JTextField();
        b10 = new javax.swing.JTextField();
        b20 = new javax.swing.JTextField();
        b21 = new javax.swing.JTextField();
        c00 = new javax.swing.JTextField();
        c01 = new javax.swing.JTextField();
        c02 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        c22 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        c20 = new javax.swing.JTextField();
        c21 = new javax.swing.JTextField();
        Opciones = new javax.swing.JComboBox<>();
        resultado = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true));

        a00.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a00ActionPerformed(evt);
            }
        });
        a00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a00KeyTyped(evt);
            }
        });

        a01.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a01KeyTyped(evt);
            }
        });

        a10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a10KeyTyped(evt);
            }
        });

        a11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a11KeyTyped(evt);
            }
        });

        a12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a12KeyTyped(evt);
            }
        });

        a02.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a02KeyTyped(evt);
            }
        });

        a20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a20KeyTyped(evt);
            }
        });

        a21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a21KeyTyped(evt);
            }
        });

        a22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        a22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        a22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a22KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese los valores de las matrices, seleccione una operación y oprime el botón de resultado:");

        b00.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b00KeyTyped(evt);
            }
        });

        b01.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b01KeyTyped(evt);
            }
        });

        b02.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b02KeyTyped(evt);
            }
        });

        b12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b12KeyTyped(evt);
            }
        });

        b22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b22KeyTyped(evt);
            }
        });

        b11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b11KeyTyped(evt);
            }
        });

        b10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b10KeyTyped(evt);
            }
        });

        b20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b20KeyTyped(evt);
            }
        });

        b21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        b21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b21KeyTyped(evt);
            }
        });

        c00.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c00.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c01.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c01.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c02.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c02.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c22.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c11.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c20.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        c21.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        c21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Opciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operación", "+", "-", "x" }));
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });

        resultado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        resultado.setText("=");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton1.setText("Limpiar matrices");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton3.setText("?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(texto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(b00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(resultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(c00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(c20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(a02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(c02, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c00, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c01, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultado))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(c20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(c21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a00ActionPerformed

    private void a00KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a00KeyTyped
        
        char a00 = evt.getKeyChar();
        
        if(Character.isLetter(a00))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a00KeyTyped

    private void a01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a01KeyTyped
        
        char a01 = evt.getKeyChar();
        
        if(Character.isLetter(a01))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a01KeyTyped

    private void a02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a02KeyTyped
        
        char a02 = evt.getKeyChar();
        
        if(Character.isLetter(a02))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a02KeyTyped

    private void a10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a10KeyTyped
        
        char exponente = evt.getKeyChar();
        
        if(Character.isLetter(exponente))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a10KeyTyped

    private void a11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a11KeyTyped
        
        char a11 = evt.getKeyChar();
        
        if(Character.isLetter(a11))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        }         
        
    }//GEN-LAST:event_a11KeyTyped

    private void a12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a12KeyTyped
        
        char a12 = evt.getKeyChar();
        
        if(Character.isLetter(a12))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a12KeyTyped

    private void a20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a20KeyTyped
        
        char a20 = evt.getKeyChar();
        
        if(Character.isLetter(a20))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a20KeyTyped

    private void a21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a21KeyTyped
        
        char a21 = evt.getKeyChar();
        
        if(Character.isLetter(a21))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a21KeyTyped

    private void a22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a22KeyTyped
        
        char a22 = evt.getKeyChar();
        
        if(Character.isLetter(a22))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_a22KeyTyped

    private void b00KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b00KeyTyped
        
        char b00 = evt.getKeyChar();
        
        if(Character.isLetter(b00))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b00KeyTyped

    private void b01KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b01KeyTyped
        
        char b01 = evt.getKeyChar();
        
        if(Character.isLetter(b01))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b01KeyTyped

    private void b02KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b02KeyTyped
        
        char b02 = evt.getKeyChar();
        
        if(Character.isLetter(b02))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b02KeyTyped

    private void b10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b10KeyTyped
        
        char b10 = evt.getKeyChar();
        
        if(Character.isLetter(b10))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b10KeyTyped

    private void b11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b11KeyTyped
        
        char b11 = evt.getKeyChar();
        
        if(Character.isLetter(b11))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b11KeyTyped

    private void b12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b12KeyTyped
        
        char b12 = evt.getKeyChar();
        
        if(Character.isLetter(b12))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b12KeyTyped

    private void b20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b20KeyTyped
        
        char b20 = evt.getKeyChar();
        
        if(Character.isLetter(b20))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b20KeyTyped

    private void b21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b21KeyTyped
        
        char b21 = evt.getKeyChar();
        
        if(Character.isLetter(b21))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b21KeyTyped

    private void b22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b22KeyTyped
        
        char b22 = evt.getKeyChar();
        
        if(Character.isLetter(b22))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_b22KeyTyped

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed

        
    }//GEN-LAST:event_OpcionesActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        
        String opciones;
        float aa00, aa01, aa02, aa10, aa11, aa12, aa20, aa21, aa22;
        float bb00, bb01, bb02, bb10, bb11, bb12, bb20, bb21, bb22;
        float cc00, cc01, cc02, cc10, cc11, cc12, cc20, cc21, cc22;
        
        aa00 = Float.parseFloat(this.a00.getText());
        aa01 = Float.parseFloat(this.a01.getText());
        aa02 = Float.parseFloat(this.a02.getText());
        aa10 = Float.parseFloat(this.a10.getText());
        aa11 = Float.parseFloat(this.a11.getText());
        aa12 = Float.parseFloat(this.a12.getText());
        aa20 = Float.parseFloat(this.a20.getText());
        aa21 = Float.parseFloat(this.a21.getText());
        aa22 = Float.parseFloat(this.a22.getText());
        
        bb00 = Float.parseFloat(this.b00.getText());
        bb01 = Float.parseFloat(this.b01.getText());
        bb02 = Float.parseFloat(this.b02.getText());
        bb10 = Float.parseFloat(this.b10.getText());
        bb11 = Float.parseFloat(this.b11.getText());
        bb12 = Float.parseFloat(this.b12.getText());
        bb20 = Float.parseFloat(this.b20.getText());
        bb21 = Float.parseFloat(this.b21.getText());
        bb22 = Float.parseFloat(this.b22.getText());
        
        opciones = Opciones.getSelectedItem().toString();
        
        switch (opciones)
        {
            case "Operación":
                texto.setText("Seleccione una operación");
                break;
            
            case "+":
                cc00 = aa00 + bb00;
                cc01 = aa01 + bb01;
                cc02 = aa02 + bb02;
                cc10 = aa10 + bb10;
                cc11 = aa11 + bb11;
                cc12 = aa12 + bb12;
                cc20 = aa20 + bb20;
                cc21 = aa21 + bb21;
                cc22 = aa22 + bb22;
                
                texto.setText("La suma de las matrices es:");
                
                c00.setText(String.valueOf(String.format("%.3f" ,cc00)));
                c01.setText(String.valueOf(String.format("%.3f" ,cc01)));
                c02.setText(String.valueOf(String.format("%.3f" ,cc02)));
                c10.setText(String.valueOf(String.format("%.3f" ,cc10)));
                c11.setText(String.valueOf(String.format("%.3f" ,cc11)));
                c12.setText(String.valueOf(String.format("%.3f" ,cc12)));
                c20.setText(String.valueOf(String.format("%.3f" ,cc20)));
                c21.setText(String.valueOf(String.format("%.3f" ,cc21)));
                c22.setText(String.valueOf(String.format("%.3f" ,cc22)));
                break;
                
            case "-":
                cc00 = aa00 - bb00;
                cc01 = aa01 - bb01;
                cc02 = aa02 - bb02;
                cc10 = aa10 - bb10;
                cc11 = aa11 - bb11;
                cc12 = aa12 - bb12;
                cc20 = aa20 - bb20;
                cc21 = aa21 - bb21;
                cc22 = aa22 - bb22;
                
                texto.setText("La resta de las matrices es:");
                
                c00.setText(String.valueOf(String.format("%.3f" ,cc00)));
                c01.setText(String.valueOf(String.format("%.3f" ,cc01)));
                c02.setText(String.valueOf(String.format("%.3f" ,cc02)));
                c10.setText(String.valueOf(String.format("%.3f" ,cc10)));
                c11.setText(String.valueOf(String.format("%.3f" ,cc11)));
                c12.setText(String.valueOf(String.format("%.3f" ,cc12)));
                c20.setText(String.valueOf(String.format("%.3f" ,cc20)));
                c21.setText(String.valueOf(String.format("%.3f" ,cc21)));
                c22.setText(String.valueOf(String.format("%.3f" ,cc22)));
                break;
                
            case "x":
                cc00 = ((aa00 * bb00) + (aa01 * bb10) + (aa02 * bb20));
                cc01 = ((aa00 * bb01) + (aa01 * bb11) + (aa02 * bb21));
                cc02 = ((aa00 * bb02) + (aa01 * bb12) + (aa02 * bb22));
                cc10 = ((aa10 * bb00) + (aa11 * bb10) + (aa12 * bb20));
                cc11 = ((aa10 * bb01) + (aa11 * bb11) + (aa12 * bb21));
                cc12 = ((aa10 * bb02) + (aa11 * bb12) + (aa12 * bb22));
                cc20 = ((aa20 * bb00) + (aa21 * bb10) + (aa22 * bb20));
                cc21 = ((aa20 * bb01) + (aa21 * bb11) + (aa22 * bb21));
                cc22 = ((aa20 * bb02) + (aa21 * bb12) + (aa22 * bb22));
                
                texto.setText("El producto de las matrices es:");
                
                c00.setText(String.valueOf(String.format("%.4f" ,cc00)));
                c01.setText(String.valueOf(String.format("%.4f" ,cc01)));
                c02.setText(String.valueOf(String.format("%.4f" ,cc02)));
                c10.setText(String.valueOf(String.format("%.4f" ,cc10)));
                c11.setText(String.valueOf(String.format("%.4f" ,cc11)));
                c12.setText(String.valueOf(String.format("%.4f" ,cc12)));
                c20.setText(String.valueOf(String.format("%.4f" ,cc20)));
                c21.setText(String.valueOf(String.format("%.4f" ,cc21)));
                c22.setText(String.valueOf(String.format("%.4f" ,cc22)));
                break;
        }
        
    }//GEN-LAST:event_resultadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        texto.setText("");
        
        a00.setText("");
        a01.setText("");
        a02.setText("");
        a10.setText("");
        a11.setText("");
        a12.setText("");
        a20.setText("");
        a21.setText("");
        a22.setText("");
        
        b00.setText("");
        b01.setText("");
        b02.setText("");
        b10.setText("");
        b11.setText("");
        b12.setText("");
        b20.setText("");
        b21.setText("");
        b22.setText("");
        
        c00.setText("");
        c01.setText("");
        c02.setText("");
        c10.setText("");
        c11.setText("");
        c12.setText("");
        c20.setText("");
        c21.setText("");
        c22.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        AyudaMatrices ayudamatrices = new AyudaMatrices();
        ayudamatrices.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JTextField a00;
    private javax.swing.JTextField a01;
    private javax.swing.JTextField a02;
    private javax.swing.JTextField a10;
    private javax.swing.JTextField a11;
    private javax.swing.JTextField a12;
    private javax.swing.JTextField a20;
    private javax.swing.JTextField a21;
    private javax.swing.JTextField a22;
    private javax.swing.JTextField b00;
    private javax.swing.JTextField b01;
    private javax.swing.JTextField b02;
    private javax.swing.JTextField b10;
    private javax.swing.JTextField b11;
    private javax.swing.JTextField b12;
    private javax.swing.JTextField b20;
    private javax.swing.JTextField b21;
    private javax.swing.JTextField b22;
    private javax.swing.JTextField c00;
    private javax.swing.JTextField c01;
    private javax.swing.JTextField c02;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c20;
    private javax.swing.JTextField c21;
    private javax.swing.JTextField c22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resultado;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
