
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio
 */
public class Sumatorias extends javax.swing.JFrame {

    /**
     * Creates new form Sumatorias
     */
    public Sumatorias() {
        super("Sumatorias");
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Opciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        veces = new javax.swing.JTextField();
        resultado = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        Sumatoria = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 8, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecciona una de las siguientes sumatorias: ");

        Opciones.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones", "Seno", "Coseno", "Exponencial" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingresa un número entero positivo para la sumatoria: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingresa el número de veces que se realizará la sumatoria: ");

        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroKeyTyped(evt);
            }
        });

        veces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vecesActionPerformed(evt);
            }
        });
        veces.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                vecesKeyTyped(evt);
            }
        });

        resultado.setText("Realizar sumatoria");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton3.setText("?");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultado)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(texto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(veces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Opciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Sumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(veces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultado)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vecesActionPerformed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroKeyTyped
        
        char numero = evt.getKeyChar();
        
        if(Character.isLetter(numero))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        }
        
    }//GEN-LAST:event_numeroKeyTyped

    private void vecesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vecesKeyTyped
        
       char exponente = evt.getKeyChar();
        
        if(Character.isLetter(exponente))
        {
            getToolkit().beep();
            evt.consume();
            resultado.setEnabled(false);
        }
        
        else
        {
            resultado.setEnabled(true);
        } 
        
    }//GEN-LAST:event_vecesKeyTyped

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        try{
            
        String opciones;
        int i;
        double x;
        int k;
        int n;
        double factorial = 1;
        double resultado = 0;
        
        opciones = Opciones.getSelectedItem().toString();
        
        x = Double.parseDouble(this.numero.getText());
        n = Integer.parseInt(this.veces.getText());
        
        switch(opciones)   
            
        {
            case "Opciones":
                texto.setText("Seleccione una opción");
                Sumatoria.setText("");
            break;
            
            case "Seno":
                if(n > 0 /*&& n <=9 && x < 10 && x > 0*/)
                {
        
                    for (k = 0; k < n; k++)
                    {
           
                        if(k > 0)
                        {
                            for(i = 1; i <= (k * 2) + 1; i++ )
                            {
                    
                                factorial = factorial * i;
                    
                            }
                        } 
                
                        resultado = resultado + ((float)Math.pow((-1), k) * ((float)(Math.pow(x, (k * 2) + 1)) / factorial));
                
                        factorial = 1;
           
                    }
            
                    texto.setText("La sumatoria de Seno con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" ,resultado)));
        
                }
                
                /*else if(n > 9 || x > 5 || x < 1)
                {
            
                    texto.setText("La sumatoria de Coseno con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" , Math.sin(x))));
                }*/
        
                else
                {
                    texto.setText("Introduzca un número de veces mayor a 0");
                    Sumatoria.setText("ERROR");
                }
                
            break;
            
            case "Coseno":
                if(n > 0 /*&& n <=9 && x < 10 && x > 0*/)
                {
        
                    for (k = 0; k < n; k++)
                    {
           
                        if(k > 0)
                        {
                            for(i = 1; i <= (k * 2); i++ )
                            {
                    
                                factorial = factorial * i;
                    
                            }
                        } 
                
                        resultado = resultado + ((float)Math.pow((-1), k) * ((float)(Math.pow(x, (k * 2))) / factorial));
                
                        factorial = 1;
                        
                    }
            
                    texto.setText("La sumatoria de Coseno con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" ,resultado)));
        
                }
                
                /*else if(n > 9 || x > 5 || x < 1)
                {
            
                    texto.setText("La sumatoria de Coseno con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" , Math.cos(x))));
                    
                }*/
        
                else
                {
                    texto.setText("Introduzca un número de veces mayor a 0");
                    Sumatoria.setText("ERROR");
                }
            break;
            
            case "Exponencial":
                if(n > 0 /*&& n <=9 && x < 10 && x > 0*/)
                {
        
                    for (k = 0; k <= n; k++)
                    {
           
                        if(k > 0)
                        {
                            for(i = 1; i <= k; i++ )
                            {
                    
                                factorial = factorial * i;
                    
                            }
                        } 
           
                        resultado = resultado + ((Math.pow(x, k) / factorial));
                
                        factorial = 1;
           
                    }
            
                    texto.setText("Sumatoria de Exponencial con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" ,resultado)));
       
                }
                
                /*else if(n > 9 || x > 5 || x < 1)
                {
            
                    texto.setText("La sumatoria de Exponencial con x = " +x+ " realizada " +n+ " veces es:");
                    Sumatoria.setText(String.valueOf(String.format("%.7f" , Math.exp(x))));
                    
                }*/
        
                else
                {
                    texto.setText("Introduzca un número de veces mayor a 0");
                    Sumatoria.setText("ERROR");
                }
            break;
        }}catch (Exception e) {JOptionPane.showMessageDialog(null, "Introduzca el tipo de dato solicitado", "Error", JOptionPane.ERROR_MESSAGE);}
        
    }//GEN-LAST:event_resultadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        AyudaSumatoria ayudasumatoria = new AyudaSumatoria();
        ayudasumatoria.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sumatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sumatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sumatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sumatorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sumatorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JTextField Sumatoria;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numero;
    private javax.swing.JButton resultado;
    private javax.swing.JLabel texto;
    private javax.swing.JTextField veces;
    // End of variables declaration//GEN-END:variables
}
